control_estudios/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from control_estudios.views import listar_cursos, crear_curso, buscar_cursos,\
    eliminar_curso, editar_curso, EstudianteListView, EstudianteCreateView,\
    EstudianteDetailView, EstudianteUpdateView, EstudianteDeleteView


urlpatterns = [
    # URLS de cursos
    path("cursos/", listar_cursos, name="lista_cursos"),
    path("crear-curso/", crear_curso, name="crear_curso"),
    path("buscar-cursos/", buscar_cursos, name="buscar_cursos"),
    path("eliminar-curso/<int:id>/", eliminar_curso, name="eliminar_curso"),
    path("editar-curso/<int:id>/", editar_curso, name="editar_curso"),
    # URLS de estudiantes
    path("estudiantes/", EstudianteListView.as_view(), name="lista_estudiantes"),
    path('estudiantes/<int:pk>/', EstudianteDetailView.as_view(), name="ver_estudiante"),
    path('crear-estudiante/', EstudianteCreateView.as_view(), name="crear_estudiante"),
    path('editar-estudiante/<int:pk>/', EstudianteUpdateView.as_view(), name="editar_estudiante"),
    path('eliminar-estudiante/<int:pk>/', EstudianteDeleteView.as_view(), name="eliminar_estudiante"),
]

# Configuración para servir archivos estáticos durante el desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proyecto2/urls.py
from django.contrib import admin
from django.urls import path, include

from proyecto2.views import saludar, saludar_con_fecha, saludar_a_usuario,\
    saludar_con_html, inicio


urlpatterns = [
    path("", inicio, name="inicio"),
    path("admin/", admin.site.urls),
    path("estudios/", include("control_estudios.urls")),
    path("saludo/", saludar),
    path("saludo-hoy/", saludar_con_fecha),
    path("saludo-html/", saludar_con_html),
]

control_estudios/models.py
from django.db import models
from django.forms import BooleanField

class Curso(models.Model):
    nombre = models.CharField(max_length=64)  
    comision = models.IntegerField()  

    def __str__(self):
        return f"{self.nombre} | {self.comision}"


class Estudiante(models.Model):
    apellido = models.CharField(max_length=256)
    nombre = models.CharField(max_length=256)
    email = models.EmailField(blank=True)
    telefono = models.CharField(max_length=20, blank=True)
    dni = models.CharField(max_length=32)
    cursos = models.ManyToManyField(Curso)  

    def __str__(self):
        return f"{self.nombre}, {self.apellido}"


class Profesor(models.Model):
    apellido = models.CharField(max_length=256)
    nombre = models.CharField(max_length=256)
    dni = models.CharField(max_length=32)
    email = models.EmailField(blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    profesion = models.CharField(max_length=128)
    bio = models.TextField(blank=True)

    def __str__(self):
        return f"{self.nombre}, {self.apellido}"


class Entregable(models.Model):
    nombre = models.CharField(max_length=256)
    fecha_entrega = models.DateTimeField(auto_now_add=True)
    esta_aprobado = models.BooleanField(default=False)  # equivalente a bool (True, False)

control_estudios/forms.py
from django import forms
from .models import Curso

class CursoFormulario(forms.ModelForm):
    class Meta:
        model = Curso
        fields = ['nombre', 'comision']


    def clean_comision(self):
        comision = self.cleaned_data.get('comision')
        if comision > 50000:
            raise forms.ValidationError("La comisión no puede ser mayor de 50000.")
        return comision

control_estudios/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from control_estudios.forms import CursoFormulario
from control_estudios.models import Curso, Estudiante

# Vistas de cursos
def listar_cursos(request):
    contexto = {
        "cursos": Curso.objects.all(),
    }
    return render(request, 'control_estudios/lista_cursos.html', contexto)

def crear_curso(request):
    if request.method == "POST":
        formulario = CursoFormulario(request.POST)

        if formulario.is_valid():
            data = formulario.cleaned_data
            nombre = data['nombre']
            comision = data['comision']

            curso = Curso(nombre=nombre, comision=comision)
            curso.save()

            return redirect('lista_cursos')
    
    else:  # GET
        formulario = CursoFormulario()

    return render(
        request=request,
        template_name='control_estudios/formulario_curso.html',
        context={'formulario': formulario}
    )

def buscar_cursos(request):
    if request.method == "POST":
        data = request.POST
        busqueda = data["busqueda"]
        cursos = Curso.objects.filter(comision__contains=busqueda)
        contexto = {
            "cursos": cursos,
        }
        return render(request, 'control_estudios/lista_cursos.html', contexto)

def eliminar_curso(request, id):
    curso = Curso.objects.get(id=id)
    if request.method == "POST":
        curso.delete()
        return redirect('lista_cursos')

def editar_curso(request, id):
    curso = Curso.objects.get(id=id)
    if request.method == "POST":
        formulario = CursoFormulario(request.POST)

        if formulario.is_valid():
            data = formulario.cleaned_data
            curso.nombre = data['nombre']
            curso.comision = data['comision']
            curso.save()
            return redirect('lista_cursos')
    else:  # GET
        inicial = {
            'nombre': curso.nombre,
            'comision': curso.comision,
        }
        formulario = CursoFormulario(initial=inicial)
    return render(
        request=request,
        template_name='control_estudios/formulario_curso.html',
        context={'formulario': formulario},
    )

# Vistas de Estudiantes
class EstudianteListView(ListView):
    model = Estudiante
    template_name = 'control_estudios/lista_estudiantes.html'

class EstudianteCreateView(CreateView):
    model = Estudiante
    fields = ('apellido', 'nombre', 'email', 'dni')
    success_url = reverse_lazy('lista_estudiantes')
    template_name = 'control_estudios/estudiante_forms.html'  

class EstudianteDetailView(DetailView):
    model = Estudiante
    success_url = reverse_lazy('lista_estudiantes')

class EstudianteUpdateView(UpdateView):
    model = Estudiante
    fields = ('apellido', 'nombre', 'email', 'dni')
    success_url = reverse_lazy('lista_estudiantes')

class EstudianteDeleteView(DeleteView):
    model = Estudiante
    success_url = reverse_lazy('lista_estudiantes')

proyecto2/views.py
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse


def saludar(request):
    saludo = "Hola bienvenido usuario"
    pagina_html = HttpResponse(saludo)
    return pagina_html


def saludar_con_fecha(request):
    hoy = datetime.now()
    saludo = f"Hola bienvenido usuario, fecha: {hoy.day}/{hoy.month}"
    pagina_html = HttpResponse(saludo)
    return pagina_html


def saludar_a_usuario(request, nombre):
    texto = f"Hola {nombre}"
    pagina_html = HttpResponse(texto)
    return pagina_html


def saludar_con_html(request):
    contexto = {
        "usuario": "Lucas"
    }
    http_responde = render(
        request=request,
        template_name='control_estudios/base.html',
        context=contexto,
    )
    return http_responde

def inicio(request):
    contexto = {
        "titulo": "Bienvenido a Control de Estudios",
        "descripcion": "Gestiona tus cursos y estudiantes de manera eficiente.",
        "enlace_cursos": "/cursos/",  
        "enlace_estudiantes": "/estudiantes/",  
    }
    return render(request, 'control_estudios/index.html', contexto)

control_estudios/templates/control_estudios/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Inicio</title>
        <!-- Favicon-->
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

    </head>

    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="https://www.google.com">Google</a>
                <a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'lista_cursos' %}">Cursos</a>
                <a class="navbar-brand" href="{% url 'lista_estudiantes' %}">Estudiantes</a>
                <a class="btn btn-primary" href="#signup">Registro</a>
            </div>
        </nav>

        <section style="padding:4rem 3rem;">
            {% block contenido %}
            {% endblock contenido %}
        </section>

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">Ayuda</a></li>
                            <li class="list-inline-item">â‹…</li>
                            <li class="list-inline-item"><a href="#!">Contacto</a></li>
                      
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Muestra del curso creado - preentrega3.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="https://twitter.com/"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.instagram.com/?hl=es"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

    </body>
</html>

control_estudios/templates/control_estudios/busq_estudiantes.html
{% extends "control_estudios/lista_estudiantes.html" %}

{% block contenido_estudiantes %}
    <p>Esta es la página de búsqueda de estudiantes.</p>
{% endblock contenido_estudiantes %}

control_estudios/templates/control_estudios/estudiante_confirm_delete.html
{% extends "control_estudios/base.html" %}

{% block contenido %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <p>¿Estás seguro de que deseas eliminar "{{ object }}"?</p>

  <input type="submit" value="Eliminar" />
</form>

<br>
<a href="{% url 'lista_estudiantes' %}">Volver lista</a>

{% endblock contenido %}

control_estudios/templates/control_estudios/estudiante_detail.html
{% extends "control_estudios/base.html" %}

{% block contenido %}

<p>
  <strong>Apellido:</strong> {{object.apellido}}
</p>
<p>
  <strong>Nombre:</strong> {{object.nombre}}
</p>
<p>
  <strong>DNI:</strong> {{object.dni}}
</p>
<p>
  <strong>Telefono:</strong> {{object.telefono}}
</p>
<p>
  <strong>Email:</strong> {{object.email}}
</p>

<br>
<a href="{% url 'lista_estudiantes' %}">Volver lista</a>

{% endblock contenido %}

control_estudios/templates/control_estudios/estudiante_forms.html
{% extends "control_estudios/base.html" %}

{% block contenido %}
    <h1>Formulario de Estudiante</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    <br>
    <a href="{% url 'lista_estudiantes' %}">Volver a la lista de estudiantes</a>
{% endblock contenido %}

control_estudios/templates/control_estudios/formulario_curso.html
{% extends "control_estudios/base.html" %}

{% block contenido %}
    <form method="post">
        {% csrf_token %}
        
        {{ formulario.as_p }}
        {{ formulario.errors }}

        <input type="submit" value="Guardar">
    </form>
    <a href="{% url 'lista_cursos' %}">Volver lista</a>
{% endblock contenido %}

control_estudios/templates/control_estudios/formulario_curso_a_mano.html
{% extends "control_estudios/base.html" %}

{% block contenido %}
    <form method="post">
        {% csrf_token %}
        
        <label for="id_nombre_curso">Nombre del curso:</label>
        <input type="text" id="id_nombre_curso" name="nombre_curso">

        <label for="id_comision">Comisión:</label>
        <input type="text" id="id_comision" name="comision">

        <input type="submit" value="Guardar">
    </form>
    <a href="{% url 'lista_cursos' %}">Volver lista</a>
{% endblock contenido %}

control_estudios/templates/control_estudios/index.html
{% extends "control_estudios/base.html" %}

{% block contenido %}
    <div class="jumbotron">
        <h1>Bienvenidos a pre entrega3</h1>
        <p>Este es un proyecto de aula. Explore nuestras opciones:</p>
        <ul>
            <li><a href="{% url 'lista_cursos' %}">Ver cursos</a></li>
            <li><a href="{% url 'lista_estudiantes' %}">Ver estudiantes</a></li>
        </ul>
    </div>
{% endblock contenido %}

control_estudios/templates/control_estudios/lista_cursos.html
{% extends "control_estudios/base.html" %}

{% block contenido %}
    <h1>Lista de cursos</h1>
    <a href="{% url 'crear_curso' %}">Crear curso</a>

    {% csrf_token %}

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Comisión</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for curso in cursos %}
                <tr>
                    <td>{{ curso.id }}</td>
                    <td>{{ curso.nombre }}</td>
                    <td>{{ curso.comision }}</td>
                    <td>
                        <a href="{% url 'editar_curso' curso.id %}">Editar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'lista_cursos' %}">Volver lista</a>
{% endblock contenido %}

control_estudios/templates/control_estudios/lista_estudiantes.html
<h1>Lista de estudiantes</h1>
<a href="{% url 'crear_estudiante' %}">Crear estudiante</a>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for alumno in object_list %}
            <tr>
                <td>{{ alumno.id }}</td>
                <td>{{ alumno.nombre }}</td>
                <td>{{ alumno.apellido }}</td>
                <td>
                    <a href="{% url 'ver_estudiante' alumno.id %}">Ver</a>
                    <a href="{% url 'editar_estudiante' alumno.id %}">Editar</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>